apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: api-gateway
          image: victorcra/masterquizz-api-gateway:c495c7c728967e400e1450dc1c574d4d358326ed
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: LOG_LEVEL
              value: "info"
            - name: USER_SERVICE_URL
              value: "http://ms-user:3000"
            - name: QUIZZ_SERVICE_URL
              value: "http://ms-quizz-management:3000"
            - name: KAFKA_BROKERS
              value: '["kafka-service:29092"]'
            - name: VALKEY_HOST
              value: "valkey-service"
            - name: VALKEY_PORT
              value: "6379"
            - name: COREPACK_HOME
              value: "/tmp/corepack"
            - name: YARN_CACHE_FOLDER
              value: "/tmp/yarn-cache"
            - name: AUTH_ACCESS_PRIVATE_KEY_PATH
              value: "/etc/auth/access_private.pem"
            - name: AUTH_ACCESS_PUBLIC_KEY_PATH
              value: "/etc/auth/access_public.pem"
          volumeMounts:
            - name: auth-keys
              mountPath: "/etc/auth"
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: auth-keys
          secret:
            secretName: masterquizz-auth-keys
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  selector:
    app: api-gateway
