# nodeLinker: node-modules (Removed to enable PnP)

packageExtensions:
  typeorm@*:
    dependencies:
      pg: "*"
  vite@*:
    dependencies:
      esbuild: "*"
      tsx: "*"
      jiti: "*"
      yaml: "*"
      "@vitejs/devtools": "*"
  vitest@*:
    dependencies:
      vite: "*"
