nodeLinker: pnp
pnpMode: strict
pnpEnableInlining: true
pnpShebang: false
pnpEnableEsmLoader: true
pnpFallbackMode: dependenciesonly

enableGlobalCache: false
cacheFolder: .yarn/cache

packageExtensions:
  typeorm@*:
    dependencies:
      pg: "*"
  vite@*:
    dependencies:
      esbuild: "*"
      tsx: "*"
      jiti: "*"
      yaml: "*"
      "@vitejs/devtools": "*"
