apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-ms-response
  newName: victorcra/masterquizz-ms-response
  newTag: 3c52ed5a2680e3d8ce90376783ad8a8f2b434d4f
