apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-ms-response
  newName: victorcra/masterquizz-ms-response
  newTag: ba00378382ec5fce05c04a7282e9ae5587935a64
