apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-ms-response
  newName: victorcra/masterquizz-ms-response
  newTag: 7c20059d5d0d57b31f53583fa41d33c160b2464f
