apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-api-gateway
  newName: victorcra/masterquizz-api-gateway
  newTag: 32cdd80c449f7730512793391202db910a2976fa
