apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-api-gateway
  newName: victorcra/masterquizz-api-gateway
  newTag: 9427d9efbdc35c2a4c60b7208ac32f47f2b7ab53
