apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-ms-quizz-management
  newName: victorcra/masterquizz-ms-quizz-management
  newTag: 2c4705f85a13267434da500d3bafda0c04ce0556
