apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-ms-quizz-management
  newName: victorcra/masterquizz-ms-quizz-management
  newTag: 56d202deec4a2db5a962a84a90a2241deb7c7726
