apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-ms-quizz-management
  newName: victorcra/masterquizz-ms-quizz-management
  newTag: 77dbe2e07e072e03e92574f98b9b2a712ca3c5c9
