apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: victorcra/masterquizz-ws-service
  newName: victorcra/masterquizz-ws-service
  newTag: 32cdd80c449f7730512793391202db910a2976fa
