apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: victorcra/masterquizz-ws-service
  newName: victorcra/masterquizz-ws-service
  newTag: 42a68008d1e8b59257b6ed10fc8ed6a8bfb6ea67
