apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: victorcra/masterquizz-ws-service
  newName: victorcra/masterquizz-ws-service
  newTag: 10819b1c8d81bfa7ab194f75f4665faa4e00c99e
