apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: victorcra/masterquizz-ws-service
  newName: victorcra/masterquizz-ws-service
  newTag: c5053be7c4406067af6c928638cd822273a9bad5
