apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: victorcra/masterquizz-ws-service
  newName: victorcra/masterquizz-ws-service
  newTag: 5c9cede32dac54a4471e0f65838b075f814cd147
