apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-ms-quizz-management
  newName: victorcra/masterquizz-ms-quizz-management
  newTag: cccd8f025e5acf8c758a8e7ac864e642588696ed
