apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-ms-quizz-management
  newName: victorcra/masterquizz-ms-quizz-management
  newTag: 95b6caf11e44e1eb21e9e2f8da0d99d8467aa002
