apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: api-gateway-cors
  namespace: masterquizz-prod
spec:
  cors:
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    accessControlAllowOriginList:
      - https://quizzmaster.com
    accessControlMaxAge: 100
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: monitoring-auth
  namespace: masterquizz-prod
spec:
  basicAuth:
    secret: monitoring-auth-secret
