apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - middlewares.yaml

secretGenerator:
  - name: traefik-auth
    literals:
      - users=admin:$apr1$k7j5w2m3$q9Z6X7V8K9L0M1N2O3P4Q5
