apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: ms-user

images:
- name: victorcra/masterquizz-ms-user
  newName: victorcra/masterquizz-ms-user
  newTag: 9ee189edf6dd758c102e5c13566db2aa0245d25f
