apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml
  - grafana.yaml
  - otel-collector.yaml
  - opensearch.yaml
  - opensearch-dashboards.yaml
  - grafana-datasources.yaml
  - grafana-dashboards-config.yaml
  - jaeger.yaml
  - rbac.yaml

configMapGenerator:
  - name: grafana-dashboards-json
    files:
      - 1-platform-overview.json=../../../../monitoring/grafana/dashboards/1-platform-overview.json
      - 2-api-gateway.json=../../../../monitoring/grafana/dashboards/2-api-gateway.json
      - 3-microservices.json=../../../../monitoring/grafana/dashboards/3-microservices.json
      - 4-kafka.json=../../../../monitoring/grafana/dashboards/4-kafka.json
