apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml
  - grafana.yaml
  - otel-collector.yaml
  - opensearch.yaml
  - opensearch-dashboards.yaml
  - grafana-datasources.yaml
  - grafana-dashboards-config.yaml
  - grafana-dashboards-json.yaml
  - jaeger.yaml
  - rbac.yaml
