apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

  - prometheus.yaml
  - grafana.yaml
resources:
  - otel-collector.yaml
  - opensearch.yaml
  - opensearch-dashboards.yaml
  - rbac.yaml
