apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-api-gateway
  newName: victorcra/masterquizz-api-gateway
  newTag: dcb2c4715663dd87b598b3f36d58cebdfd7ec1fd
