apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-api-gateway
  newName: victorcra/masterquizz-api-gateway
  newTag: bca188cb41857088821e722540c430cdfcdd99d5
