apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-api-gateway
  newName: victorcra/masterquizz-api-gateway
  newTag: a86732e93f2b59b4dbfad7c04f05ebf5b772371c
