apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-office
  labels:
    app: front-office
    allow-traefik: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-office
  template:
    metadata:
      labels:
        app: front-office
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: front-office
          image: victorcra/masterquizz-front-office:1.0.0
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: next-cache
              mountPath: /app/.next/cache
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          command: ["/bin/sh", "-c"]
          args: ["ls -R /app && sleep 3600"]
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: next-cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: front-office
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: front-office
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-office-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: masterquizz-prod-global-ratelimit@kubernetescrd,masterquizz-prod-security-headers@kubernetescrd
spec:
  rules:
    - host: quizz-master.cyrus-ag.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-office
                port:
                  number: 80
