apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-office
  labels:
    app: front-office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-office
  template:
    metadata:
      labels:
        app: front-office
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: front-office
          image: victorcra/masterquizz-front-office:88cb7330c05551aa225005dbd5707e680b0e1d6a
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: front-office
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: front-office
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-office-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-office
                port:
                  number: 80
