apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-ms-response
  newName: victorcra/masterquizz-ms-response
  newTag: 098aefc50b0743a60dd843f4dc5c7b0b5392a290
