apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-ms-response
  newName: victorcra/masterquizz-ms-response
  newTag: 4eca7db598c18e4d5c8f35f2e5a4c03b62924c24
