name: Docker Hub Cleanup

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup MasterQuizz Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, ms-user, ms-quizz-management]

    steps:
      - name: Delete old tags for ${{ matrix.service }}
        uses: lostlink/docker-cleanup@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/masterquizz-${{ matrix.service }}

          keep-last: 3

          older-than: 30 days

          exclude-tags: latest
