name: QuizzApp CI
on:
  push:
    branches: [feat/CI-1.0, main]
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest`
    outputs:
      api-gateway: ${{ steps.filter.outputs.api-gateway }}
      common: ${{ steps.filter.outputs.common }}
      ms-quizz-management: ${{ steps.filter.outputs.ms-quizz-management }}
      ms-user: ${{ steps.filter.outputs.ms-user }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes in packages
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api-gateway:
                - 'packages/api-gateway/**'
                - '!packages/api-gateway/README.md'
            common:
                - 'packages/common/**'
                - '!packages/common/README.md'
            ms-quizz-management:
                - 'packages/ms-quizz-management/**'
                - '!packages/ms-quizz-management/README.md'
            ms-user:
                - 'packages/ms-user/**'
                - '!packages/ms-user/README.md'
  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [api-gateway, common, ms-quizz-management, ms-user]
    defaults:
      run:
        working-directory: ./packages/${{ matrix.package }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        shell: bash
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.14.0"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Run tests if defined
        run: |
          if npm run | grep -q 'test'; then
          echo "Test script found, running tests"
          yarn test

          else
          echo "No test script, skipping"
          fi
